name: GitHub Decluttering Report

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  declutter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and Run Declutter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        cargo build --release
        ./target/release/declutter

    - name: Commit and push report
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add declutter-report.md
        git commit -m "Add decluttering report [skip ci]"
        git push origin HEAD
